export const FETCH_CURRENTLY_PLAYING = 'FETCH_CURRENTLY_PLAYING';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_SELECTED_MOVIE_DETAILS = 'FETCH_SELECTED_MOVIE_DETAILS';
