export const SET_MOVIE_LOADING = 'SET_MOVIE_LOADING';
export const SET_CURRENTLY_PLAYING = 'SET_CURRENTLY_PLAYING';
export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
